### ISSUE TITLE
Error when java player enter whenever there is bedrock user already insie

### ISSUE THREAD

**Issue by cupang-afk** [GeyserExtras/GeyserExtras#13]
```
[07:35:57 WARN]: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component org.geysermc.mcprotocollib.protocol.data.game.PlayerListEntry.getDisplayName()'
[07:35:57 WARN]:        at GeyserExtras.jar//dev.letsgoaway.geyserextras.core.handlers.java.JavaPlayerInfoUpdateInjector.translate(JavaPlayerInfoUpdateInjector.java:42)
[07:35:57 WARN]:        at GeyserExtras.jar//dev.letsgoaway.geyserextras.core.handlers.java.JavaPlayerInfoUpdateInjector.translate(JavaPlayerInfoUpdateInjector.java:18)
[07:35:57 WARN]:        at Geyser-Spigot [2.5.0-SNAPSHOT].jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:90)
[07:35:57 WARN]:        at Geyser-Spigot [2.5.0-SNAPSHOT].jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:70)
[07:35:57 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[07:35:57 WARN]:        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[07:35:57 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[07:35:57 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[07:35:57 WARN]:        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[07:35:57 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583
```

gameplay seem fine though

geyser extras version v2.0.0-ALPHA-12

**Comment by letsgoawaydev** [comment]
I am aware of this issue
