### ISSUE TITLE
Geyser Extras doesn't working

### ISSUE THREAD

**Issue by Beq4u2** [GeyserExtras/GeyserExtras#4]
So Geyser itself works and stuff but when i use command /ge or so it says that I can't do that because of the error.
When i looked up in to the console it spams me this:
```
[16:33:55] [Server thread/WARN]: [GeyserExtras] Task #66 for GeyserExtras v1.20.6-v1.1.1 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class dev.letsgoaway.geyserextras.spigot.BedrockPlayer
	at dev.letsgoaway.geyserextras.spigot.GeyserExtras.update(GeyserExtras.java:106) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4085-Spigot-b754dcc-d9209ed]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4085-Spigot-b754dcc-d9209ed]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1339) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4085-Spigot-b754dcc-d9209ed]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:391) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4085-Spigot-b754dcc-d9209ed]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1242) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4085-Spigot-b754dcc-d9209ed]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1054) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4085-Spigot-b754dcc-d9209ed]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4085-Spigot-b754dcc-d9209ed]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: Class org.bukkit.entity.EntityType does not have member field 'org.bukkit.entity.EntityType CHEST_MINECART' [in thread "Server thread"]
	at dev.letsgoaway.geyserextras.spigot.BedrockPlayer.<clinit>(BedrockPlayer.java:409) ~[?:?]
	... 9 more
```

Is there a way to fix this or the problem is because my server is on 1.20.4?

**Comment by letsgoawaydev** [comment]
geyser extras does not support 1.20.4

**Comment by letsgoawaydev** [comment]
I've just announced the future update of GeyserExtras 2.0 which will support versions from 1.12+. You can get updates for it on my discord here: https://discord.gg/ekvDjYZKsU

**Comment by AriqMicin** [comment]
> I've just announced the future update of GeyserExtras 2.0 which will support versions from 1.12+. You can get updates for it on my discord here: https://discord.gg/ekvDjYZKsU

yayyy
