### ISSUE TITLE
Could not pass event BlockPlaceEvent

### ISSUE THREAD

**Issue by Zo0mPlay** [GeyserExtras/GeyserExtras#5]
**Hello, I encountered such an error in the console, I do not know what to do:**

[10:10:01 ERROR]: Could not pass event BlockPlaceEvent to GeyserExtras v1.21.0-v1.1.2

java.lang.NullPointerException: null

at java.base/java.util.Objects.requireNonNull(Objects.java:220) ~[?:?]

at GeyserExtras.jar/dev.letsgoaway.geyserextras.spigot.BedrockPlayer.onPlayerBlockPlace(BedrockPlayer.java:544) ~[GeyserExtras.jar:?]

at GeyserExtras.jar/dev.letsgoaway.geyserextras.spigot.EventListener.onPlayerBlockPlace(EventListener.java:139) ~[GeyserExtras.jar:?]

at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor345.execute(Unknown Source) ~[?:?]

at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-38-1f5db50]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-38-1f5db50]

at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-38-1f5db50]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at org.bukkit.craftbukkit.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:449) ~[paper-1.21.jar:1.21-38-1f5db50]

at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:487) ~[paper-1.21.jar:1.21-38-1f5db50]

at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:607) ~[paper-1.21.jar:1.21-38-1f5db50]

at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1871) ~[paper-1.21.jar:1.21-38-1f5db50]

at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[paper-1.21.jar:1.21-38-1f5db50]

at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[paper-1.21.jar:1.21-38-1f5db50]

at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:36) ~[paper-1.21.jar:1.21-38-1f5db50]

at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-38-1f5db50]

at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-38-1f5db50]

at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-38-1f5db50]

at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1478) ~[paper-1.21.jar:1.21-38-1f5db50]

at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-38-1f5db50]

at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-38-1f5db50]

at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1456) ~[paper-1.21.jar:1.21-38-1f5db50]

at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1449) ~[paper-1.21.jar:1.21-38-1f5db50]

at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-38-1f5db50]

at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1408) ~[paper-1.21.jar:1.21-38-1f5db50]

at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1529) ~[paper-1.21.jar:1.21-38-1f5db50]

at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[paper-1.21.jar:1.21-38-1f5db50]

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-38-1f5db50]

at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]

**Comment by letsgoawaydev** [comment]
please try the latest version and see if this issue still occurs, sorry i didnt get to responding to your issue
